### ISSUE TITLE
可否考虑下支持客户的自定义域名

### ISSUE THREAD

**Issue by aresroyal** [aliyun/oss-browser#101]
支持获取http地址时可以使用用户的自定义域名，这样更加高效，也更加方便，应用也更加广泛。

**Comment by vnobo** [comment]
+1

**Comment by liyang8** [comment]
+1
刚想过来提这个问题~

**Comment by istevenshen** [comment]
+1

**Comment by duan007a** [comment]
目前没有开放api用来获取bucket对应绑定的cdn域名绑定的自定义域名，这个需求我们这边也会综合考虑，感谢您的反馈

**Comment by ddkk3000** [comment]
用户自己填入不就行了吗？不需要自动获取呀
________________________________

**Comment by vnobo** [comment]
> 目前没有开放api用来获取bucket对应绑定的cdn域名绑定的自定义域名，这个需求我们这边也会综合考虑，感谢您的反馈

开放一个窗口,用户自定义设置,这个不难吧

**Comment by ddkk3000** [comment]
用户难道连这个都无法自己判断，还需要程序判断么？

（我和我的小伙伴们都惊呆了）

________________________________

发件人： Albert Luo<mailto:notifications@github.com>
发送时间： 2018-09-26 17:25
收件人： aliyun/oss-browser<mailto:oss-browser@noreply.github.com>
抄送： ddkk3000<mailto:lixiaozhe@live.com>; Comment<mailto:comment@noreply.github.com>
主题： Re: [aliyun/oss-browser] 可否考虑下支持客户的自定义域名 (#101)

@vnobo<https://github.com/vnobo> 增加一个窗口设置是可以的，但是如果用户自己填写错了，我们是没法判断用户是否填写正确的。加也是可以加的。

**Comment by szkzn** [comment]
+10086，产品迭代那么多个版本，还要等多久，这个是现实需求，不少用户用的是CDN+OSS的方式，因为CDN有流量包，OSS走内网到阿里云ECS，这样可以节省部分流量费，也能加速下载和访问。

**Comment by lichangwei** [comment]
非常需要这个功能，添加一个可选填的CDN域名字段即可，每次自己手动替换CDN域名太麻烦了。如果你们愿意接受这个功能但是没有时间，我可以来做。

**Comment by szkzn** [comment]
1.9.1版本是有这个功能，但是很不灵活，并且也是失效了，通过cname方式登陆填入自定义域名，只能看到你所选的cname自定义域名的bucket，要切换其他bucket，对不起，请重登＋重新输入，极其麻烦，并且生成下载地址也不会替换成cname域名了，已经几个月了

**Comment by lichangwei** [comment]
@szkzn 感谢你的回复，抱歉我才看到。

在这个功能上，可以因为缺少一些API，无法完美地实现，但是我们并不需要那么完美。可以在AK登录页面让我输入CDN域名，然后获取资源地址时自动替换成我填写的域名即可，这样这个功能就很好了，总比每次拷贝了地址以后手动替换好的多。不能因为没有100分的方案，还拒绝掉80分的方案。好失望。  @duan007a

**Comment by lichangwei** [comment]
> @vnobo 增加一个窗口设置是可以的，但是如果用户自己填写错了，我们是没法判断用户是否填写正确的。加也是可以加的。

现在你们没有提供这种功能，我每次上传了资源以后，要获取资源地址，然后手动替换，岂不是更容易出错。作为一个工具的提供者，更多的是提供一种可能性可行性，如果能限制一下让用户不出错最好，如果不好限制，只能让用户自己注意。Office软件那么牛逼，也没能防止我写错别字，对吧？

**Comment by szkzn** [comment]
你们这个自定义域名功能会间歇性抽风，有时候不会替换，甚至一直卡在生成地址的过程中

你们想的太复杂了，用户正常方式登陆即可，然后你们在设置界面提供一个标签页，里面可以自行绑定多个域名到获取到的bucket列表上，

例：登陆后获取到buckwt列表后：假设为

abc bucket 对应1.cn
123 bucket 2.cn
451ris bucket 3.cn
dkkaj bucket 4.cn
 你们在设置提供获取到的4个bucket设置选项，用户可以一一对应设置不同的bucket的对应的自定义域名,保存到本地即可，下次同一ak登陆，加载该ak设置自定义域名的数据，在获取下载地址时，把oss域名部分根据用户设置的值进行替换（比如正则提取oss域名部分，简单的拼接替换字符串），最终显示和获取的地址已经是经过替换的就行了

我推测issue主之使用这个麻烦版的自定义域名功能时，地址没替换，oss客户端抽风，一定几率会替换，一定几率原样显示，因为这个问题我遇到过很多次

**Comment by xiusin** [comment]
产品是根据客户需求来的， 这么强势， 自定义域名选项都不开放

**Comment by zxiaofan** [comment]
没有自定义域名确实很恼火，自己支持了一把，欢迎各位试用。
[zxiaofan/oss-browser](https://github.com/zxiaofan/oss-browser/releases/tag/1.9.5.1)
扩展“获取地址”操作（PS：官方一直不优化，只有自己动手了，建议官方尽快支持）：
- 获取地址支持自定义域名；
- 获取地址支持获取markdown格式地址，直接可用于书写Markdown文章； 
- 尽量和官方版本保持同步更新，版本号后加.1，如官方VERSION=1.9.5，则此处VERSION=1.9.5.1；
- 需要使用此版本的朋友，可从releases直接下载，或者自行下载源码编译；
**示例** ：   
![1910ossBrower_zxiaofan.jpg](http://tc.zxiaofan.com/tc/a/1910/1910ossBrower_zxiaofan.jpg)

**Comment by PeterRao** [comment]
已经支持
