### ISSUE TITLE
OOM when uploading large number of files.

### ISSUE THREAD

**Issue by rprinceley** [aliyun/oss-browser#112]
oss-browser (v1.6.4) uses too much memory while trying to upload a folder with a large number of files (tiled GIS imagery with about 80,000 files).

`Windows successfully diagnosed a low virtual memory condition. The following programs consumed the most virtual memory: oss-browser.exe (9080) consumed 59417841664 bytes...`

**Comment by luozhang002** [comment]
@rprinceley 同issue#108
