### ISSUE TITLE
make run 启动失败

### ISSUE THREAD

**Issue by w1021508536** [aliyun/oss-browser#117]
custom=./custom npm run dev
'custom' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
make: *** [makefile:23: run] Error 1

make i 成功 make build 成功 最后一步的make run 就失败了

**Comment by dream1995** [comment]
请问一下 解决了么

**Comment by duan007a** [comment]
https://github.com/aliyun/oss-browser/tree/master/custom    请完全按照文档步骤操作

**Comment by liutianzeng** [comment]
请问这个问题解决了吗？我也遇到相同的问题了

**Comment by ghost** [comment]
我也遇到这个问题了，请问楼主解决了么。
