### ISSUE TITLE
希望支持通过homebrew安装mac版

### ISSUE THREAD

**Issue by qin** [aliyun/oss-browser#118]
ossbrowser很好用，团队都喜欢。希望支持通过homebrew安装mac版，因为公司里团队所有其他预装软件都是通过homebrew脚本安装到mac电脑的，如果能也加上ossbrowser就更好了

https://brew.sh/

**Comment by duan007a** [comment]
暂不支持

**Comment by BenBao93** [comment]
Any update on this? Would be great to have an easy way to install OSS browser on mac
