### ISSUE TITLE
总是卡在校验文件上

### ISSUE THREAD

**Issue by WillCup** [aliyun/oss-browser#120]
拷贝大量文件时，总是卡在校验小文件上，卡住不动，也不报错

**Comment by 1019272778** [comment]
是上传还是拷贝呢？

**Comment by luozhang002** [comment]
@WillCup 这种问题确实偶尔会出现，自测的时候有时候很难复现。针对这种情况 ，建议（1）单击右侧的暂停重试（2）推出OSSbrowser再来。因为用的是断点续传 。（3）校验中的时候确保本地文件不要改动。（4）打开调试控制台，单击左上角的logo10次，弹出调试界面。里面关于文件校验的地方，我们打印的有日志，如果能够复现的话，可提供下相关日志。（5）针对这些小文件单独上传是否还会出现这种问题。

**Comment by luozhang002** [comment]
@WillCup 现在目前我们已经在做本地日志存储了，到时候遇到问题可以及时提供日志。方便定位问题。
