### ISSUE TITLE
OSS Browser无法上传文件

### ISSUE THREAD

**Issue by Mainvooid** [aliyun/oss-browser#125]
系统：win10_x64

问题：
- 可以创建目录但是无法上传文件和目录。显示正在添加到上传队列，然后后续就没有反应了，以管理员启动也是无法上传。

**Comment by meteormatt** [comment]
貌似没人管这里的问题。
这个工具我还是决定不用了。

**Comment by sinri** [comment]
+1 Windows too

**Comment by duan007a** [comment]
这个项目线上有很多用户在用，我们在上线之前也都会经过严格的质量测试。希望各位能提供一下不能使用时的错误信息，我们也好帮助大家解决问题。

**Comment by Mainvooid** [comment]
@meteormatt 刚才更新到v1.7.2版本没问题了，有上传状态显示，上传之后，目标目录下也有显示文件。之前的情况是没有错误信息，上传后没有反应，不显示文件，没有任何提示，检查没有上传成功。@duan007a
