### ISSUE TITLE
能build能run，但打包出mac下的软件后，一直停在开始的进度圈上

### ISSUE THREAD

**Issue by SaltedfishCaptain** [aliyun/oss-browser#132]
能build能run，run成功之后也能正常使用，但打包出mac下的软件后，一直停在开始的进度圈上
回退到直接clone下来的代码进行打包也是一样

![image](https://user-images.githubusercontent.com/13551681/43034366-b9a3e650-8d0d-11e8-9bb1-480c41d849c2.png)

**Comment by duan007a** [comment]
这种时候可以打开mac上面的控制台应用，查看一下具体的log输出是什么
