### ISSUE TITLE
上传asar文件会被默认成目录上传

### ISSUE THREAD

**Issue by hxkuc** [aliyun/oss-browser#134]
上传asar文件会被默认成目录上传，在网页版的后台不会出现这样的问题

**Comment by duan007a** [comment]
oss-browser内部读取资源是从asar中读取，需要识别为目录才可以。如果你有上传asar文件的需求，可以选择网页版的控制台或者ossutil

**Comment by hxkuc** [comment]
如果是asar压缩一下再上传呢，到服务器再解压一下子？我asar是可以上传的啊，下载也可以，你试试用这个包electron-patch-fs应该可以解决

**Comment by duan007a** [comment]
暂时不做支持

**Comment by hxkuc** [comment]
好吧
