### ISSUE TITLE
NetworkingError:Network Failure

### ISSUE THREAD

**Issue by hjfeng1988** [aliyun/oss-browser#137]
确定机器网络没问题，win7 64位 1.7.1
已重装软件，重启，删除C盘“oss"相关文件，回退版本1.7.0，都是相同的错误提示。

**Comment by duan007a** [comment]
遇到这种情况可以连续点击左上角图标超过10次，可以调出调试界面。查看network里面的网络请求失败的请求，然后尝试在你机器的命令行curl以下请求失败的那个url，这种问题一般都是出在机器访问不到host导致

**Comment by hjfeng1988** [comment]
还有这么一个隐藏功能
已找到问题，电脑有vpn设置了全局代理，修改了IE的代理。

**Comment by JiaxYau** [comment]
> 还有这么一个隐藏功能
> 已找到问题，电脑有vpn设置了全局代理，修改了IE的代理。

请问你是怎么设置的？我也遇到了同样的问题。

**Comment by hjfeng1988** [comment]
IE浏览器关闭代理
