### ISSUE TITLE
一个7MB大小的图片无法预览

### ISSUE THREAD

**Issue by yuancao5566** [aliyun/oss-browser#139]
有没有说明超过多大的图片无法预览啊，我在控制台可以正常预览，在oss browser里面就不行了

**Comment by yuancao5566** [comment]
经过测试，发现小于5MB的图片可以正常预览，只要大于等于5MB就无法预览

**Comment by duan007a** [comment]
是的，超过5MB的图片不支持预览，可以通过下载到本地之后再查看
