### ISSUE TITLE
获取http地址时生成的地址url有误，路径的 "/" 全部被 "%2F" 替换

### ISSUE THREAD

**Issue by kurt-yeah** [aliyun/oss-browser#144]
如题，不知道为啥。应该是更新版本后出的问题

**Comment by aosting** [comment]
同样的问题

**Comment by szkzn** [comment]
为什么需要把 "/"转义，"/"的ASCII 十六进制是 “2F”，下载时无法获取正确的文件名，如迅雷U享版，360极速浏览器内置下载，谷歌浏览器69.0正式版……况且我存放文件时已经自行规避特殊字符了，找不到理由需要转移，不是传参，只是一个简单的下载请求，搞得那么复杂何必呢？

**Comment by szkzn** [comment]
![url 1](https://user-images.githubusercontent.com/30108874/45447640-b9cf7a80-b702-11e8-93c1-5f441c5a2e45.png)

**Comment by szkzn** [comment]
![qq 20180913031322](https://user-images.githubusercontent.com/30108874/45447745-1d59a800-b703-11e8-9371-0b69dd744f21.png)
转义后，下载的文件名前面会加上一堆路径
形如 路径+文件名的形式
我手动把转义的%2F替换回 “/” 直接获取下载的文件名，现在好别扭...

**Comment by stjava** [comment]
+10086

**Comment by duan007a** [comment]
请先使用1.7.1版本，您反馈的这个问题我们将在下个版本中修复。
