### ISSUE TITLE
Download failed: "failed to open local file:EPERM: operation not permitted, open"

### ISSUE THREAD

**Issue by chrislong365** [aliyun/oss-browser#147]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
When trying to pull files off of OSS I am unable to download them into the Documents and Pictures folder (not an extensive list). 

Error: "failed to open local file:EPERM: operation not permitted, open"...

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Open oss browser
2. Select a file to download
3. Download file
4. Select download location as Documents
5. Error

**What is the expected behavior?**
File downloads normally

**System Configuration**
OSS Browser version: 1.7.2
Windows 10 Pro 64bit
Windows build: 17134.228

**Comment by duan007a** [comment]
sorry I can not reproduce the issue.I suggest you try run oss-browser  as admin.
