### ISSUE TITLE
建议把上传下载进度框下移到底部

### ISSUE THREAD

**Issue by istevenshen** [aliyun/oss-browser#150]
oss browser 在文件很多的时候，上传下载进度框总是会把部分的文件挡住了，能不能参考 FileZilla 把进度表放到最下面？

![qq](https://user-images.githubusercontent.com/26101369/45672058-c23c1100-bb59-11e8-881d-61a0bda19b56.png)

**Comment by duan007a** [comment]
可以点击进度框右上角的叉号将进度框收到底部的
