### ISSUE TITLE
能否添加大于5MB的图片也可以预览的功能

### ISSUE THREAD

**Issue by yuancao5566** [aliyun/oss-browser#154]
因为有大量的高清图片存储，每次都要下载下来才能看到图片内容，能否支持在oss 客户端里直接预览，即便预览的不是原图也可以啊

**Comment by luozhang002** [comment]
@这个已经排期在做了，下个版本发布

**Comment by luozhang002** [comment]
@yuancao5566 这个目前已经在1.7.4针对大文件做了一个简单的压缩预览。
