### ISSUE TITLE
Download speed slow 

### ISSUE THREAD

**Issue by jitsadhya19** [aliyun/oss-browser#156]
![image](https://user-images.githubusercontent.com/29581190/46992199-87140a00-d126-11e8-8b48-eade731988e5.png)
this is my download speed as per ookla speedtest 91 Mbps 
![image](https://user-images.githubusercontent.com/29581190/46992217-a6129c00-d126-11e8-9320-2a84eea2a30c.png)
this is the speed i am getting in OSS. maximum 700 Kbps. 
I used to get higher. could this be resolved ?

**Comment by luozhang002** [comment]
@jitsadhya19 你可以看下这边文章，OSS带宽限制相关的，https://help.aliyun.com/knowledge_detail/65440.html
