### ISSUE TITLE
能否增加文件在线处理功能

### ISSUE THREAD

**Issue by yangbinnnn** [aliyun/oss-browser#157]
**示例**

0. 用户配置在线处理服务地址为`https://online-process.com/preview`
1. 用户右击`1.mp4`，选择自定义在线处理
2. 拼接URL, 如`https://online-process.com/preview?name=1.mp4&url=<file download url encode>`
3. 调用系统默认浏览器打开URL，展示在线处理内容

**注**

这样可以方便通过在线服务来扩展对文件的处理功能，如在线预览office文档，视频播放等等，同时数据可以不落地

**Comment by luozhang002** [comment]
@yangbinnnn OSS Browser工具本身主要功能就是为存储为用户提供常用文件的上传下载管理工作，目前我们只支持文本文件的编辑，图片和视频的预览功能。
