### ISSUE TITLE
Ubuntu 64 最新版本 bug

### ISSUE THREAD

**Issue by freedog8** [aliyun/oss-browser#162]
打开后是白屏
![image](https://user-images.githubusercontent.com/21093659/48175869-c2ca7a00-e348-11e8-9721-71bd4a8d7d25.png)

**Comment by freedog8** [comment]
@luozhang002 是这样的：
我需要从阿里云上下载一些数据，从github上直接下载OSS-browser的64位UBUNTU版本。
解压之后在OSS-browser文件夹运行 ./oss-browser命令。然后就一直显示这个空白页

**Comment by luozhang002** [comment]
@freedog8  目前这个问题，本地ubuntu一直没有复现，因为每次版本发版前，各个版本都是手工确认能否运行的。

**Comment by duchengyao** [comment]
相同的问题，干净的ubuntu18 第一次运行时提示
Gtk-Message: 23:59:17.069: Failed to load module "canberra-gtk-module"
安装libcanberra-gtk-module后 再次运行白屏。

**Comment by duchengyao** [comment]
然后我下载了旧版 1.70， work

**Comment by duchengyao** [comment]
重启电脑后偶尔会运行成功。

白屏时应该是有内容的，可以狂点左上角启动Debug模式，也能看到内容

**Comment by khjtony** [comment]
我也遇到了这个问题. 我是全新安装ubuntu18.04, KDE桌面, 下载oss-browser并且用chmod添加了权限后还是白屏. 有什么办法我可以上传log吗

**Comment by imagineer83** [comment]
同样的问题，UBUNTU 18.04.4

**Comment by luxingran** [comment]
i also have this, can u solve it?

**Comment by jriy** [comment]
启动的时候加参数   --disable-gpu，就不会显示空白了
