### ISSUE TITLE
文件夹上传时 是否可以默认不将.开头的文件上传，如macos的.DS_Store文件

### ISSUE THREAD

**Issue by guerrillacaptain** [aliyun/oss-browser#164]

**Comment by luozhang002** [comment]
@guerrillacaptain  这个逻辑是可以做，但是意义感觉不大，而且这种文件用户完全可以自己操控的上传前删除或者删除后删除，而且这种文件一般几乎很小很小的，甚至有的用户可能也需要这种文件
