### ISSUE TITLE
文件上传不上去-getaddrinfo ENOTFOUND..... 

### ISSUE THREAD

**Issue by zhaohaoran123** [aliyun/oss-browser#166]
内网环境，浏览器设置了代理，window 64 位版本，能正常登录，下载，但是不能上传，报错截图如下
![info](https://user-images.githubusercontent.com/15125158/48385640-31814c00-e72a-11e8-8d82-6755ca92a1b4.png)

**Comment by luozhang002** [comment]
@zhaohaoran123 请确保你当前网络能否ping通这个域名。

**Comment by luozhang002** [comment]
@zhaohaoran123 这种问题一般是网络不通的问题

**Comment by cutie6** [comment]
如何解决的？？？？
