### ISSUE TITLE
获取CDN地址什么时候能加上，产品迭代那么多个版本了

### ISSUE THREAD

**Issue by szkzn** [aliyun/oss-browser#185]
早在1.5.x我就有这个需求，到github也看到了关于CDN加速域名的issue，你们回复没有相关API，当时后面也跟了一堆评论，大意是这个用户自己判断就行了，你们只需要给个设置界面的GUI，用户自行填入自己的CDN加速域名地址，在获取下载地址界面相应的显示替换为CDN地址就行了。
然而截止到现在2019-1-7 12:28:28，没有任何动静，每次更新日志都没看到相关信息，还要等多久才能加上？你们已经迭代到1.8.1了，数十个版本过去了迟迟不见踪影

不可能每次都复制黏贴自定义域名的CDN地址自行手工替换吧，几个文件还好，数十个或更多不就凉凉了，麻烦和费时?

下面有相关需求的可以在下面回复评论，让官方看到我们的需求

**Comment by szkzn** [comment]
+10086，产品迭代那么多个版本，还要等多久，这个是现实需求，不少用户用的是CDN+OSS的方式，因为CDN有流量包，OSS走内网到阿里云ECS，这样可以节省部分流量费，也能加速下载和访问。

**Comment by luozhang002** [comment]
@szkzn 这个目前我们我们已经开发好了，这周会和一个新功能一起上线。拟定版本1.9.0 类似下图这种
![111](https://user-images.githubusercontent.com/5653578/50751994-26a8ea80-1287-11e9-945a-611095dfae91.jpg)
用户必须在li mian里面输入正确的域名和bucket，这里的bucket和域名是用户手动绑定的。

**Comment by xjoylu** [comment]
是的

**Comment by chuangbo** [comment]
这个填 CDN 地址后，无法登录，提示网络超时
