### ISSUE TITLE
1.9.0预览图片失败

### ISSUE THREAD

**Issue by wcj343169893** [aliyun/oss-browser#189]
1.9.0预览图片失败，扫码可以查看，直接点预览就提示无法预览
![image](https://user-images.githubusercontent.com/502789/51068737-6728af80-165d-11e9-958e-9159739e919c.png)
打开调试模式，
提示：SignatureDoesNotMatch
The request signature we calculated does not match the signature you provided. Check your key and signing method.
既然文件列表都能打开，而且文件也是公共可读的

**Comment by luozhang002** [comment]
@wcj343169893  采用什么方式登录的，能截哥图吗？

**Comment by tanfeng** [comment]
> 1.9.0预览图片失败，扫码可以查看，直接点预览就提示无法预览
> ![image](https://user-images.githubusercontent.com/502789/51068737-6728af80-165d-11e9-958e-9159739e919c.png)
> 打开调试模式，
> 提示：SignatureDoesNotMatch
> The request signature we calculated does not match the signature you provided. Check your key and signing method.
> 既然文件列表都能打开，而且文件也是公共可读的

我也遇到了这个问题，刚更新的1.9.0之后无法预览。然后登录重新更新一下就可以了，用的AK登录方式。

**Comment by huyx1501** [comment]
我也碰到同样的问题，1.8.X版本正常，用1.9.X版本无法预览。调试模式显示

160b6a1a-faa1-4752-a4de-900b96af2453.jpg:1 GET http://[省略]/160b6a1a-faa1-4752-a4d…Uvp&Signature=shX[省略]n3n6Y%3D&x-oss-request-payer=requester 403 (Forbidden)

**Comment by tangwan** [comment]
v1.9.x遇到这个问题,退出重新登陆即可.
![image](https://user-images.githubusercontent.com/15011585/53383685-6fda0880-39b3-11e9-83a4-64d2429af177.png)

**Comment by cb360** [comment]
> 我也碰到同样的问题，1.8.X版本正常，用1.9.X版本无法预览。调试模式显示
> 
> 160b6a1a-faa1-4752-a4de-900b96af2453.jpg:1 GET http://[省略]/160b6a1a-faa1-4752-a4d…Uvp&Signature=shX[省略]n3n6Y%3D&x-oss-request-payer=requester 403 (Forbidden)
> 
> 必须重新登录才可以，不知道算不算BUG

是的，我也是如此
