### ISSUE TITLE
1.9.0自定义域名如何使用？

### ISSUE THREAD

**Issue by tanfeng** [aliyun/oss-browser#191]
请问1.9.0自定义域名如何使用？没找到介绍。

**Comment by zxiaofan** [comment]
官方版本貌似有bug，自己支持了一把，欢迎试用。
[zxiaofan/oss-browser](https://github.com/zxiaofan/oss-browser/releases/tag/1.9.5.1)
扩展“获取地址”操作（PS：官方一直不优化，只有自己动手了，建议官方尽快支持）：
- 获取地址支持自定义域名；
- 获取地址支持获取markdown格式地址，直接可用于书写Markdown文章； 
- 尽量和官方版本保持同步更新，版本号后加.1，如官方VERSION=1.9.5，则此处VERSION=1.9.5.1；
- 需要使用此版本的朋友，可从releases直接下载，或者自行下载源码编译；
**示例** ：   
![1910ossBrower_zxiaofan.jpg](http://tc.zxiaofan.com/tc/a/1910/1910ossBrower_zxiaofan.jpg)
