### ISSUE TITLE
Bloated package size for Mac

### ISSUE THREAD

**Issue by lyrids** [aliyun/oss-browser#193]
请是用符号链接取代重复的文件拷贝. 这是手工修正符号链接后的效果, 能节省大约300MB 的磁盘空间. 

示意如下:

LY-MBPR-2:Frameworks ly$ pwd
/Applications/oss-browser.app/Contents/Frameworks
LY-MBPR-2:Frameworks ly$ tree -L 2

├── Electron\ Framework.framework
 │   ├── Electron\ Framework -> Versions/Current/Electron\ Framework
 │   ├── Libraries -> Versions/Current/Libraries
 │   ├── Resources -> Versions/Current/Resources
 │   └── Versions
├── Mantle.framework
 │   ├── Headers -> Versions/Current/Headers
 │   ├── Mantle -> Versions/Current/Mantle
 │   ├── Modules -> Versions/Current/Modules
 │   ├── Resources -> Versions/Current/Resources
 │   └── Versions
├── ReactiveCocoa.framework
 │   ├── Headers -> Versions/Current/Headers
 │   ├── Modules -> Versions/Current/Modules
 │   ├── ReactiveCocoa -> Versions/Current/ReactiveCocoa
 │   ├── Resources -> Versions/Current/Resources
 │   └── Versions
├── Squirrel.framework
 │   ├── Headers -> Versions/Current/Headers
 │   ├── Modules -> Versions/Current/Modules
 │   ├── Resources -> Versions/Current/Resources
 │   ├── Squirrel -> Versions/Current/Squirrel
 │   └── Versions
├── oss-browser\ Helper\ EH.app
 │   └── Contents
├── oss-browser\ Helper\ NP.app
 │   └── Contents
└── oss-browser\ Helper.app
    └── Contents

**Comment by luozhang002** [comment]
the same question in #184
