### ISSUE TITLE
为什么提示远程线程注入?

### ISSUE THREAD

**Issue by langhuaxing** [aliyun/oss-browser#200]
![image](https://user-images.githubusercontent.com/38237092/52405217-c5826a00-2b05-11e9-80cf-0b1535f421d9.png)
请看图片.360提示

**Comment by luozhang002** [comment]
这个跟程序本身没啥关系把，360自己的规则把

**Comment by langhuaxing** [comment]
远程线程注入是一种非常手段，把dll隐藏到其他进程隐藏自己，正常情况下不需要这种操作。
不知道是用的cef框架还是我的电脑有病毒

**Comment by luozhang002** [comment]
@langhuaxing 没有出现这种提示
