### ISSUE TITLE
文件夹显示不了修改时间

### ISSUE THREAD

**Issue by oldthreefeng** [aliyun/oss-browser#211]
![image](https://user-images.githubusercontent.com/38313565/56487795-fec85480-650e-11e9-80d4-12b847b43970.png)
文件可以显示修改时间，但是文件夹没有修改时间，能否有方法显示修改时间

**Comment by luozhang002** [comment]
@oldthreefeng 发个你的邮箱过来，备注下的你的操作系统，我打个临时的包先发给你使用下，正式的会可能要晚一点上。

**Comment by oldthreefeng** [comment]
> @oldthreefeng 发个你的邮箱过来，备注下的你的操作系统，我打个临时的包先发给你使用下，正式的会可能要晚一点上。

louisehong4168@gmail.com     
win10系统64位
谢谢啦

**Comment by luozhang002** [comment]
@oldthreefeng 已发
