### ISSUE TITLE
图片”无法预览“

### ISSUE THREAD

**Issue by ansonhorse** [aliyun/oss-browser#216]
### 系统
MacOS
### 版本
1.9.1

### 描述
如图所示，全部图片都是”无法预览“
![image](https://user-images.githubusercontent.com/7548142/58870775-65868380-86f3-11e9-9e6f-c66dc00437a4.png)

**Comment by Ari1c** [comment]
@ansonhorse 你好，对于你这种情况:1.你打开控制台看下报错信息（topbar上设置按钮里有开启调试，点击logo10次）同时check下localStorage中show-request-pay字段是否为NO，可以根据localStorage.setItem()来修改2.退出登陆在界面预设OSS路径输入oss://后是否勾选请求者付费模式(不勾选)。此上是我们所知道的情况，如有别的情况请贴下图片。

**Comment by ansonhorse** [comment]
@Ari1c 退出重新登录，可以正常预览了
