### ISSUE TITLE
1.9.3新建Bucket时区域没有西南1(成都)

### ISSUE THREAD

**Issue by filtercai** [aliyun/oss-browser#230]
版本1.9.3，新建Bucket时区域没有西南1(成都)，但是在web控制台已经可以选择西南1(成都)了。

![image](https://user-images.githubusercontent.com/14989013/60392361-7b8d3580-9b33-11e9-8f43-70eb630b56e5.png)

**Comment by Ari1c** [comment]
@filtercai 现在暂时没有创建Bucket成都的区域，我们会尽快支持。谢谢反馈

**Comment by Ari1c** [comment]
@filtercai 1.9.4开放了成都bucket区域
