### ISSUE TITLE
Mac 下更新版本时卡主不动，无法更新

### ISSUE THREAD

**Issue by jiangkang** [aliyun/oss-browser#239]
![image](https://user-images.githubusercontent.com/12570868/60805392-876f9c00-a1b2-11e9-85bf-f901a10ed2fe.png)

在触发更新应用的时候，会弹出这个框，进度条走完之后，就卡主不动了。

操作系统：OSX 10.14.5

**Comment by Ari1c** [comment]
@jiangkang 
![image](https://user-images.githubusercontent.com/33024188/60873518-1fc85800-a269-11e9-9976-83aa24405f0d.png) 尝试一下

**Comment by Ari1c** [comment]
@jiangkang 
![image](https://user-images.githubusercontent.com/33024188/60873769-79c91d80-a269-11e9-9a9f-930159115b02.png) 你可以这么试一下，如果不可以https://oss-attachment.cn-hangzhou.oss.aliyun-inc.com/oss-browser/1.9.4/oss-browser-darwin-x64.zip这个是我们最新1.9.4版本链接

**Comment by Ari1c** [comment]
@jiangkang 
![image](https://user-images.githubusercontent.com/33024188/60873913-be54b900-a269-11e9-9602-65a1809a963b.png) 你可以这么试一下，如果不可以
  https://oss-attachment.cn-hangzhou.oss.aliyun-inc.com/oss-browser/1.9.4/oss-browser-darwin-x64.zip
这是我们最新的1.9.4版本链接

**Comment by jiangkang** [comment]
@Ari1c 问题解决了，谢谢
