### ISSUE TITLE
希望添加一个上传zip后自动解压的功能，在太多碎文件的情况下，上传太慢了

### ISSUE THREAD

**Issue by JimsC** [aliyun/oss-browser#248]

**Comment by Ari1c** [comment]
@JimsC 你完全可以上传zip文件之后手动来进行解压

**Comment by Ari1c** [comment]
@JimsC 不支持上传zip之后自动解压功能，谢谢反馈（可以根据你上传的zip下载之后手动解压）

**Comment by JimsC** [comment]
是这样的，我有一大批资源文件，每次上传我都只会上传更新部分，但是很多，上千个，客户端也只会更新自己需要的资源，上传zip再下载zip太不现实了，我也看过oss的api，没有这样的接口，能不能帮我转达下我的需求给oss的产品经理？谢谢了！

**Comment by luozhang002** [comment]
@JimsC OSSBrower是不支持上传自动解压的，可以体验下OSS控制台结合函数计算实现的自动解压功能
