### ISSUE TITLE
win10打不开ossbrowser了

### ISSUE THREAD

**Issue by tulongxCodes** [aliyun/oss-browser#254]
<img width="879" alt="WX20190903-103848@2x" src="https://user-images.githubusercontent.com/12908403/64140454-10175b00-ce37-11e9-8c86-2664de8a91fb.png">

ossbrowser版本：64位，1.9.5，1.9.4 都不行

昨天都还可以打开，今早提醒升级，然后更新之后，弹窗报错。我就从github下载新的版本。删除原来的，或者是覆盖，都打不开了。

**Comment by Ari1c** [comment]
@tulongxCodes 下载链接win64的 （https://oss-attachment.cn-hangzhou.oss.aliyun-inc.com/oss-browser/1.9.5/oss-browser-win32-x64.zip）你再尝试一下。本地我刚下载win 64是能够打开的

**Comment by tulongxCodes** [comment]
em...
很神奇的一幕，我下载了zip包，在win10里面没有安装任何加压工具，但是win10可以双击进入压缩包，然后直接拖出来。之前下载的版本我也是这么操作的，没有问题，可以打开。

今天同样的操作就不行了。

然后刚才我安装了解压工具 7zip，然后再尝试就可以打开了。

这个是什么问题。。
