### ISSUE TITLE
Windows 上传后目录不对

### ISSUE THREAD

**Issue by IsaacZhi** [aliyun/oss-browser#27]
在 Windows 下面上传到目录里面之后分隔符出错。
比如在目录 video/2017/04/20170420043/ 里面上传了 053.jpg
变成  video\2017\04\20170420043\053.jpg

**Comment by chro73** [comment]
嗯，win7 64bit下，同样的问题，上传的所有文件都放在了根目录。
跟郁闷的是，我为了测试上传，随便抓了一个目录扔上去，却不幸抓到了本软件的resources目录。
结果是我用了一个小时也没能把上传的文件删除光，明明目录下只有两个文件，上传上去变成了数千个，用本软件删除时直接导致电脑假死10分钟

**Comment by aochant** [comment]
同样的问题，上传没法用，建议发新版之前，先测试一下好吗？

**Comment by aleelock** [comment]
感谢提醒，已经fix。
前天老婆生孩子，一直在医院陪护，实在是抱歉，没能及时fix。
以后会加强各个平台的测试。

**Comment by chro73** [comment]
测试了一下，ok了。顺便恭喜楼主。
官方客户端，应该多些人维护呀
