### ISSUE TITLE
下载大量文件时，browser逐渐失去响应

### ISSUE THREAD

**Issue by YangZhang4065** [aliyun/oss-browser#272]
我在内网通过OSS browser下载几个包含了10万+图片的文件夹时browser逐渐失去响应。
下载刚刚开始开始时速度还蛮快的，随着完成任务数量和queued下载任务的增加，界面的响应速度逐渐变慢，下载速度也从开始的1M/s跌到20K/s。

**Comment by PeterRao** [comment]
下载 https://help.aliyun.com/document_detail/61872.html?spm=5176.8465980.0.0.4e701450Kn7Wve 试下。

**Comment by PeterRao** [comment]
最新版本 1.10.0
