### ISSUE TITLE
更新后无法上传文件

### ISSUE THREAD

**Issue by sdlzhd** [aliyun/oss-browser#29]
昨天更新了1.2。1版本，发现可以删除文件，但是不能上传文件，一直提示
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.

**Comment by zuoge85** [comment]
我尝试是用 阿里云账号的ak 和子账户ak 都不能成功上传！

**Comment by aleelock** [comment]
已经修复： https://github.com/aliyun/oss-browser/commit/a89960bd98d5602c8bc119888d84936e3ef0b66c
