### ISSUE TITLE
自定义 Endpoint 出现  Signature Does Not Match

### ISSUE THREAD

**Issue by sarkrui** [aliyun/oss-browser#297]
OSS 控制面板已开启全地域上传加速了，在 OSS-browser 使用 AK 登陆，使用默认云是可以登陆的（说明 Keyid 和 Keysecret 是正确的）
Endpoint 替换成 `自定义: http://<替换为自己 bucket 名>.aliyuncs.com`
```
SignatureDoesNotMatch:The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

**Comment by wtto00** [comment]
> Endpoint：选择登录的地域域名。
> - 默认：使用默认的 Endpoint 登录。
> - 自定义：输入 Endpoint 信息，填写 http 或 https 加对应地域的 Endpoint，选择使用 http 或 https 方式登录。例如 `https://oss-cn-beijing.aliyuncs.com`。地域域名信息请参见 访问域名和数据中心。
> - cname：可使用绑定的自定义域名登录。绑定自定义域名请参见绑定自定义域名。

[看官方文档](https://help.aliyun.com/document_detail/61872.html)
自定义不要添加自己的bucket名称

**Comment by sarkrui** [comment]
![](https://i.loli.net/2020/03/19/D3rz8lSMYcVIPym.png)
可能是地表加速节点比较特殊吧，没有 [bucket name] 是 ping 不通的

**Comment by wtto00** [comment]
@sarkrui 登陆界面填写不带bucket的，软件所使用的SDK内部登陆的时候会自动添加上bucket，你自己加上bucket，软件内部又添加一个，这样登陆地址正确才怪！！bucket name写在oss预设路径里面。
不太明白，阿里云官方文档写的不是很清楚吗，不看文档吗，看不明白吗，文档还给出了个自定义的示例，比着抄还不行吗？再次强调[看官方文档](https://help.aliyun.com/document_detail/61872.html)
> 例如 https://oss-cn-beijing.aliyuncs.com

看文档！看文档！看文档！

**Comment by sarkrui** [comment]
累了。我截图里并没有加 bucket。

**Comment by sarkrui** [comment]
已解决。
使用 AK + 自定义 Endpoint 登录时，`预设OSS路径` 为必须项，建议用户切换成自定义_ Endpoint 时，自动将预设 OSS 路径切换为必填项，这点再官方文档和 OSS-browser 的界面都没有提及，因此造成困扰了。
