### ISSUE TITLE
为什么OSS-browser上传文件之后，文件的属性发生改变

### ISSUE THREAD

**Issue by wdc63** [aliyun/oss-browser#306]
上传文件后，文件的最后修改日期发生改变。这对用oss作为同步盘的用户影响很大，同步软件将本地软件和云端软件识别为不同文件。

**Comment by PeterRao** [comment]
目前这个无法实现，oss目前的 LastModified 由上传时间决定，无法修改。这个目前只能通过oss的meta信息来做了，需要额外的开发定制。
