### ISSUE TITLE
移动文件时，不要修改最后修改时间

### ISSUE THREAD

**Issue by LJLCarrien** [aliyun/oss-browser#313]
前景：在window系统中，复制黏贴剪切文件，修改日期都是与原来一致的。
因为存在一种情况：查询文件的时候，是根据文件最后修改时间的，但又由于文件太多，在经过一顿移动归类后，最后修改时间变成了操作时的时间。

1、如果没有对内容做修改，不改最后修改时间。
2、复制粘贴，不改最后修改时间
3、如果1、2均无法实现，点移动黏贴，不改最后修改时间。
4、如果以上都不能实现，给个勾选框，绝不修改最后修改时间。

我尝试过自行编译该项目，但是在make i 时就报错了....
在此寻求帮助，希望能调整/增加相关功能

**Comment by PeterRao** [comment]
复制功能用的 OSS 的 copyObject 的 [API] (https://help.aliyun.com/document_detail/31979.html?spm=a2c4g.11186623.6.1646.604965d3DBjdB9) ，这个 API 不支持修改LastModified
