### ISSUE TITLE
切换自有域名不会更新 URL

### ISSUE THREAD

**Issue by NeverMin** [aliyun/oss-browser#319]
Ubuntu 18.04 amd64 
OSS browser 1.11.0

**Comment by lvpai** [comment]
更新截图:
![ossissue_hd](https://user-images.githubusercontent.com/64124920/82315725-4ebd6780-99fe-11ea-8445-941ca179d9db.gif)

**Comment by imyellow** [comment]
我也是，希望有个选项可以记住，不要每次都打开手动切换。
