### ISSUE TITLE
获取STS时如果policy中Resource带有*号则无法登录

### ISSUE THREAD

**Issue by ylmotol7** [aliyun/oss-browser#32]
acs:oss:*:*:bk-file/lz/*

错误信息：
<Error>
  <Code>AccessDenied</Code>
  <Message>Access denied by authorizer's policy.</Message>
  <RequestId>59908DF1686D42D05D441B2E</RequestId>
  <HostId>bk-file.oss-cn-hangzhou.aliyuncs.com</HostId>
</Error>

**Comment by aleelock** [comment]
请先按照 https://github.com/aliyun/oss-browser/blob/master/authToken.md 试一下。
