### ISSUE TITLE
ak历史可以导出吗

### ISSUE THREAD

**Issue by williamqian** [aliyun/oss-browser#332]
换了台电脑，原电脑有很多ak登陆历史

**Comment by PeterRao** [comment]
这个评估了下，不太会做
1. 需求不是很普遍
2. 现在oss browser没有太完整的安全登录校验机制，只是简单的ak进行授权。如果有导出功能，安全性无法保证。
如果强需求，可基于oss browser进行定制开发。

**Comment by williamqian** [comment]
好的，最后我是通过直接复制旧电脑上的`用户目录\AppData\Roaming\oss-browser`到新电脑对应目录实现的。

**Comment by lichangwei** [comment]
@williamqian 好办法，谢谢
