### ISSUE TITLE
请问OSS授权能否做到Bucket下的目录级别？

### ISSUE THREAD

**Issue by cyroby** [aliyun/oss-browser#34]
我这边有个问题，如果一个Bucket是多个用户进行作业，那么如何控制让他们相互隔离查看？

**Comment by aleelock** [comment]
有2种方案：

1. 可以给子用户授权： https://github.com/aliyun/oss-browser#4-授权给子用户--子用户登录， 具体步骤： 选择要授权的目录--> 更多--> 简化Policy授权（可以指定只读或可写）, 选择子用户名，或者新建子用户并授权。然后使用子用户的AK登录并指定目录的oss地址，即可。

2. 可以使用临时token(目前token过期时间最大为1小时)：选择要授权的目录--> 更多-->生成授权码（可以指定只读或可写），可以用授权码登录客户端即可。

**Comment by cyroby** [comment]
谢谢指点，已经找到了。提个小建议，能否在用户浏览到到某个目录下的时候不禁用“更多”的按钮？有些操作实际上可以默认对浏览到当前目录操作的。例如Window下进入目录后可以右击属性进行安全编辑，而不是对其默认禁用。
