### ISSUE TITLE
bug feedback: OSS浏览器目录与文件显示混乱

### ISSUE THREAD

**Issue by echoiron** [aliyun/oss-browser#341]
> version:1.11.0

- 目前oss显示的文件和目录是按照字符顺序排列的

- 建议：是否可以将目录全部显示在一起，文件则显示在目录下面，这样就不需要单独去搜索某个目录了

**Comment by PeterRao** [comment]
list 接口不会先返回目录的，目前的顺序其实就是oss server的返回。不过可以考虑对已经返回的结果进行前端排序。
