### ISSUE TITLE
windows版v1.11.0 文件设置软链后下载提示“文件校验不匹配”

### ISSUE THREAD

**Issue by chenke91** [aliyun/oss-browser#347]
windows版v1.11.0 文件设置软链后下载提示“文件校验不匹配”，mac版下载该文件正常

![image](https://user-images.githubusercontent.com/6261549/88524568-18b6e800-d02c-11ea-89e6-4b02d66b1c34.png)

**Comment by beajer** [comment]
v1.13.0版本已修复
