### ISSUE TITLE
若干bug与建议

### ISSUE THREAD

**Issue by tuzi3040** [aliyun/oss-browser#35]
1.设置中邮件发送设置，stmp应为smtp。这个问题在阿里邮箱app也存在，麻烦那边也说一下，我发邮件反馈没理我。
2.简化policy授权中，授权给 选择 子用户，且后面选择 新建一个 时，授权给 切换为 用户组 或 角色 后，新建子用户时有的 新用户名 和 发送AK 选项仍存在。后面选择任意已存在子用户，再切换则不会出现此问题。
3.建议增加发送获取的http地址到邮箱功能。
4.建议增设新用户用户名 随机生成 选项，可以自定义随机生成的用户名的格式。

**Comment by tuzi3040** [comment]
建议在简化policy授权时可自定义编写授权和对预置policy进行修改。

**Comment by tuzi3040** [comment]
建议集成类似驻云开发的OSS客户端中的RAM授权功能。

**Comment by aleelock** [comment]
多谢提醒和建议，已经安排开发中
