### ISSUE TITLE
增加“新建“文件按钮

### ISSUE THREAD

**Issue by ziyunfei** [aliyun/oss-browser#37]
也就是可以通过对话框输入的形式创建纯文本格式的 object。用上传的话，必须先在本地新建个文件。

**Comment by tuzi3040** [comment]
感觉没必要啊......_(´ཀ`」 ∠)_

**Comment by aleelock** [comment]
文件预览和文本文件修改，只是一个辅助功能。新建文本文件的功能，暂时不会增加。
