### ISSUE TITLE
本地make run 启动失败

### ISSUE THREAD

**Issue by ghost** [aliyun/oss-browser#370]
提示custome不是内部或外部命令

**Comment by beajer** [comment]
如果是windows系统，在Makefile文件的
`run:
	custom=$(CUSTOM) npm run dev`
改为
`run:
	set custom=$(CUSTOM) npm run dev`

**Comment by ghost** [comment]
> 如果是windows系统，在Makefile文件的
> `run: custom=$(CUSTOM) npm run dev`
> 改为
> `run: set custom=$(CUSTOM) npm run dev`

感谢你的回答，但是我试了下没有报错也没有反应 只是在dos输出了一行set custom=./custom npm run dev
