### ISSUE TITLE
为什么我设置了系统环境变量：NODE_OPTIONS=--max-http-header-size=10000后，ossbrowser就无法启动了

### ISSUE THREAD

**Issue by redabc** [aliyun/oss-browser#374]
为什么我设置了系统环境变量：NODE_OPTIONS=--max-http-header-size=10000后，ossbrowser就无法启动了

**Comment by chengqiwu** [comment]
@redabc 我也遇到这个问题了，请问你解决了嘛？

**Comment by PeterRao** [comment]
目前 oss browser 的node版本为8.x，设置NODE_OPTIONS 会导致node无法执行
