### ISSUE TITLE
如何设置文件的下载名字？

### ISSUE THREAD

**Issue by gouchaoer** [aliyun/oss-browser#375]
ossClient.multipartUpload(oss_key, file, {
        parallel: parallel,
        partSize: partSize,
        'content-disposition': `attachment; filename=${encodeURIComponent(filename)}`,
        progress: onMultipartUploadProgress
    })

我在上传的时候想设置下载的名字，但是用上面的代码没法设置

**Comment by PeterRao** [comment]
设置header里面的 content-disposition

js sdk 问题，到 js  sdk那边的issue提问
