### ISSUE TITLE
Not working on Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by Mr-LiuDC** [aliyun/oss-browser#391]
```
$ ./oss-browser 
./oss-browser: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

**Comment by timokiller** [comment]
`sudo apt-get install libgconf-2-4 `
install and fixed

**Comment by Mr-LiuDC** [comment]
@timokiller  

Thanks.

**Comment by lihexin88** [comment]
> `sudo apt-get install libgconf-2-4 `
> install and fixed

fixed! Thanks

**Comment by gocpplua** [comment]
> `sudo apt-get install libgconf-2-4 `

fixed! Thank you

**Comment by dannyhenry** [comment]
> `sudo apt-get install libgconf-2-4 ` install and fixed

fixed! thanks!!
