### ISSUE TITLE
在内网中使用oss浏览器，提示文件校验不匹配

### ISSUE THREAD

**Issue by duhongle** [aliyun/oss-browser#397]
在内网中使用oss浏览器，

v1.9.5 可以正常下载文件，升级版本后下载文件，提示文件校验不匹配，请删除文件重新下载。
测试过 v1.13.0  v1.14.0版本

**Comment by PeterRao** [comment]
内网用户，钉钉联系下值班同学看下

**Comment by novNorthSea** [comment]
公司内网部署使用依然提示 文件校验不匹配，请删除文件重新下载。
