### ISSUE TITLE
建议对oss browser增加对按时间的倒序排序，想看最新的文件，只能一直往下拉滚轮，太难用了

### ISSUE THREAD

**Issue by czxin788** [aliyun/oss-browser#400]
建议对oss browser增加对按时间的倒序排序，想看最新的文件，只能一直往下拉滚轮，太难用了

**Comment by PeterRao** [comment]
这个oss 服务本身不支持文件排序，所以只靠oss borwser是无法实现的。

**Comment by yoyo837** [comment]
那OSS那边内部提交一下功能诉求支持时间排序呗
