### ISSUE TITLE
1.14.0 按名称前缀过滤 bug

### ISSUE THREAD

**Issue by ElfSundae** [aliyun/oss-browser#405]
![image](https://user-images.githubusercontent.com/526008/116532762-3397ef00-a913-11eb-8f30-73104e86b1a7.png)

按名称前缀过滤后，文件列表里的文件名也不显示前缀了，删除时显示的文件名也没有前缀了，不过好在最终操作（下载、删除）的是实际文件。

![image](https://user-images.githubusercontent.com/526008/116532743-2e3aa480-a913-11eb-9333-cbb23753daca.png)

![image](https://user-images.githubusercontent.com/526008/116532727-2844c380-a913-11eb-806b-3437b67ae434.png)

**Comment by PeterRao** [comment]
已修复
