### ISSUE TITLE
win10 无法删除文件夹，但在重命名后可以删除

### ISSUE THREAD

**Issue by lizhiyu-me** [aliyun/oss-browser#409]

**Comment by PeterRao** [comment]
无法删除的报错是什么

**Comment by lizhiyu-me** [comment]
> 无法删除的报错是什么

没有报错，应该是要删除的文件夹里面的文件比较多，进度条卡住没有反应。
我现在用ossutil来操作了

**Comment by PeterRao** [comment]
用的什么版本，最新版本删除这块有些优化。
文件夹很多的话，是需要删除比较长时间

**Comment by PeterRao** [comment]
之前重命名空文件夹会出现该问题，新版已经修复，再试下。
