### ISSUE TITLE
make mac 后无法启动Error: Cannot find module 'electron-log'

### ISSUE THREAD

**Issue by rocing** [aliyun/oss-browser#415]
开发调试可以运行 
make mac 打包后无法运行
Uncaught Exception:
Error: Cannot find module 'electron-log'
at Module._resolveFilename (module.js:485:15)
at Function.Module._resolveFilename

**Comment by PeterRao** [comment]
在dist目录执行下npm install

**Comment by rocing** [comment]
> 在dist目录执行下npm install

好的 谢谢
