### ISSUE TITLE
v1.2.3 中 bucket 的 endpoint 不对

### ISSUE THREAD

**Issue by ziyunfei** [aliyun/oss-browser#42]
现在请求的是`http://creatives-assets.cn-hangzhou.aliyuncs.com/?delimiter=%2F&marker=&prefix=`
正确的应该是`http://creatives-assets.cn-hangzhou.oss.aliyun-inc.com/?delimiter=%2F&marker=&prefix=`
![image](https://user-images.githubusercontent.com/1276859/30947340-dab394d6-a3ce-11e7-9290-e190e248bee8.png)

**Comment by aleelock** [comment]
登录界面可以修改endpoint模板,  改成： http://{region}.oss.aliyun-inc.com

**Comment by ziyunfei** [comment]
问题我有使用多种 endpoint 的 bucket 呀
