### ISSUE TITLE
从1.2.2开始，Mac版本登录后NetworkingError

### ISSUE THREAD

**Issue by suruoxi** [aliyun/oss-browser#53]
Mac 10.13.1， 从1.2.2开始的版本，登录打开bucket后，显示内容为空。 提示 NetworkingError: Network Failure

区域为： oss-cn-hangzhou-zmf.aliyuncs.com 

登录其他区域没有此问题

**Comment by aleelock** [comment]
可以参照这个登录：  https://github.com/aliyun/oss-browser/blob/master/docs/aklogin.md#2-专有云登录样例
