### ISSUE TITLE
关于获取文件地址

### ISSUE THREAD

**Issue by tuzi3040** [aliyun/oss-browser#58]
部分目录、文件名含有空格等字符，建议在获取时转换为html编码否则无法正常访问

**Comment by aleelock** [comment]
目前已经转化过的了。能举个具体的例子吗？

**Comment by tuzi3040** [comment]
1.3.1版本没有转换，1.3.2因为无法本地build所以没看。
就是空格、[]等没有转换成%开头的编码.

**Comment by tuzi3040** [comment]
@aleelock 1.3.3版本也没有。
类似"BD 1280x720 x264 AAC"的内容中的空格在URL和二维码中都没有被编码。

**Comment by aleelock** [comment]
1.4.0版本，已经修复。

**Comment by tuzi3040** [comment]
已修复，感谢

**Comment by carli0215** [comment]
在这里修复的问题，在1.91版本又出现了，还没有上一个版本稳定好用呢
[img]https://i.imgur.com/6PYASrH.jpg[/img]
