### ISSUE TITLE
使用授权码登陆后，无法预览图片

### ISSUE THREAD

**Issue by tootwo2** [aliyun/oss-browser#61]
![image](https://user-images.githubusercontent.com/6477685/33301915-910b5c20-d433-11e7-89f4-9241a95d4c51.png)
![image](https://user-images.githubusercontent.com/6477685/33301929-add68e2e-d433-11e7-9c91-5154e8eb419c.png)

**Comment by aleelock** [comment]
1.4.0版本，图片预览已经修复。
