### ISSUE TITLE
上传不支持目录上传

### ISSUE THREAD

**Issue by shixinyu** [aliyun/oss-browser#77]
上传只能上传文件，不能上传目录。
之前的老版本OSS-1.2.1是支持上传目录的（Powered By驻云科技）

**Comment by skhe** [comment]
@shixinyu 我也发现点击上传按钮后，没法儿选中文件夹。不过文件夹可以通过拖拽上传。

**Comment by aleelock** [comment]
可以拖拽文件夹上传
