### ISSUE TITLE
请问如何查看文件目录的大小？  能否预览Bucket的基础信息？

### ISSUE THREAD

**Issue by robyle** [aliyun/oss-browser#79]
#OSS的基础数据
![oss](https://user-images.githubusercontent.com/11662528/34858715-c6d93e42-f749-11e7-9789-e03ec4be2aa8.png)

**Comment by aleelock** [comment]
这个是OSS控制台服务端统计的数据，目前oss browser直接调用OSS public api，没有服务端统计这些数据。
目录大小预览可以排期开发。
