### ISSUE TITLE
希望能提供更改文件域名的相关配置

### ISSUE THREAD

**Issue by xuruiray** [aliyun/oss-browser#80]
由于绑定了阿里 CDN ， 每个图片地址域名都是 CDN 配置的域名
使用 oss-browser 时还要，复制地址，然后再修改域名，很麻烦

**Comment by duan007a** [comment]
目前没有开放api用来获取bucket对应绑定的cdn域名，这个需求我们这边也会综合考虑，感谢您的反馈

**Comment by luozhang002** [comment]
同 issue 101

**Comment by luozhang002** [comment]
@xuruiray  @szkzn 同issue101
