### ISSUE TITLE
自动升级不成功

### ISSUE THREAD

**Issue by tianxing0923** [aliyun/oss-browser#86]
每次弹出升级提示，点击“已经下载成功，现在安装并重启应用”后，关闭重打开并没有升级成功，然后再次弹出，非常影响使用，每次要我重新下载包后再覆盖，我使用的是win7 x64

**Comment by ChangedenCZD** [comment]
没成功过。win10 x64

**Comment by EdisonSu768** [comment]
same issue here

mac os 10.13.3
