### ISSUE TITLE
可否增加下载文件时候，自动跳过已存在的文件

### ISSUE THREAD

**Issue by zj0713001** [aliyun/oss-browser#95]
根据Content-Length和LastModified判断即可~

**Comment by WillCup** [comment]
问下这个功能已经支持了吗？如果支持了怎样设置呢

**Comment by luozhang002** [comment]
@zj0713001  下载这种行为完全是用户主动触发行为，难道我还要去遍历用户本地已经存在的文件去判断，工具的角度来说完全没有多大意义的。
